-- MySQL Script generated by MySQL Workbench
-- Вт 09 янв 2024 08:23:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema likemind
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema likemind
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `likemind` ;
USE `likemind` ;

-- -----------------------------------------------------
-- Table `likemind`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_users_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

USE `likemind` ;

-- -----------------------------------------------------
-- procedure fill_users
-- -----------------------------------------------------

DELIMITER $$
USE `likemind`$$
CREATE PROCEDURE `fill_users` (
	users_cnt INT
)
BEGIN
	DECLARE id INT DEFAULT 1;

	DELETE FROM users;
    ALTER TABLE users AUTO_INCREMENT=1;

	WHILE (id <= users_cnt) DO
    
		call users_insert(CONCAT("user", id),
						  CONCAT("user", id, "@mail.ru"),
						  CONCAT("user", id, "pass"),
                          CURRENT_TIMESTAMP,
                          CURRENT_TIMESTAMP);
		
        SET id = id + 1;
    
    END WHILE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure users_insert
-- -----------------------------------------------------

DELIMITER $$
USE `likemind`$$
CREATE PROCEDURE `users_insert` (
	username VARCHAR(45),
	email VARCHAR(45),
    password VARCHAR(256),
    created_at DATETIME,
    updated_at DATETIME
)
BEGIN

	INSERT INTO users (username, email, password, created_at, updated_at)
    VALUES (username, email, password, created_at, updated_at);

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
