-- MySQL Script generated by MySQL Workbench
-- Чт 18 янв 2024 22:14:55
-- Model: LikeMind    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema likemind
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema likemind
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `likemind` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `likemind` ;

-- -----------------------------------------------------
-- Table `likemind`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `firstname` VARCHAR(45) NULL,
  `about` VARCHAR(512) NULL,
  `sex` VARCHAR(1) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `likemind`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `lat` FLOAT NOT NULL,
  `lon` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `limited` TINYINT(1) NOT NULL,
  `max_members` INT NULL DEFAULT 4,
  `description` VARCHAR(1024) NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `likemind`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `likemind`.`users_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`users_events` (
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `event_id`),
  INDEX `fk_users_events_role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_users_events_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_events_event_id_idx` (`event_id` ASC) VISIBLE,
  UNIQUE INDEX `UNIQUE` (`user_id` ASC, `event_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_events_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `likemind`.`roles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_events_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `likemind`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_events_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `likemind`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `likemind`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `URN` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`image_id`),
  UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC) VISIBLE,
  UNIQUE INDEX `URN_UNIQUE` (`URN` ASC) VISIBLE,
  INDEX `fk_images_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `likemind`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `likemind` ;

-- -----------------------------------------------------
-- Placeholder table for view `likemind`.`profile_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likemind`.`profile_view` (`username` INT, `email` INT, `firstname` INT, `about` INT);

-- -----------------------------------------------------
-- procedure fill_users
-- -----------------------------------------------------

DELIMITER $$
USE `likemind`$$
CREATE PROCEDURE `fill_users` (
	users_cnt INT
)
BEGIN
	DECLARE id INT DEFAULT 1;

	DELETE FROM users;
    ALTER TABLE users AUTO_INCREMENT=1;

	WHILE (id <= users_cnt) DO
    
		call users_insert(CONCAT("user", id),
						  CONCAT("user", id, "@mail.ru"),
						  CONCAT("user", id, "pass"));
		
        SET id = id + 1;
    
    END WHILE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure users_insert
-- -----------------------------------------------------

DELIMITER $$
USE `likemind`$$
CREATE PROCEDURE `users_insert` (
	username VARCHAR(45),
	email VARCHAR(45),
    password VARCHAR(256)
)
BEGIN

	INSERT INTO users (username, email, password)
    VALUES (username, email, password);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure events_insert
-- -----------------------------------------------------

DELIMITER $$
USE `likemind`$$
CREATE PROCEDURE `events_insert` (
	title VARCHAR(45),
    lat FLOAT,
    lon FLOAT,
    limited TINYINT(1)
)
BEGIN

	INSERT INTO events (title, lat, lon, limited)
    VALUES (title, lat, lon, limited);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure fill_events
-- -----------------------------------------------------

DELIMITER $$
USE `likemind`$$
CREATE PROCEDURE `fill_events` (
    events_cnt INT
)
BEGIN
    DECLARE id INT DEFAULT 1;
    DECLARE lat FLOAT DEFAULT 55.751574;
    DECLARE lon FLOAT DEFAULT 37.573856;

DELETE FROM events;
    ALTER TABLE events AUTO_INCREMENT=1;

    WHILE (id <= events_cnt) DO
    
        call events_insert(CONCAT("event", id),
                          lat,
                          lon,
                          0);
        
        SET id = id + 1;
        SET lat = lat + 0.001;
        SET lon = lon + 0.001;

    END WHILE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `likemind`.`profile_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `likemind`.`profile_view`;
USE `likemind`;
CREATE  OR REPLACE VIEW `profile_view` AS SELECT username, email, firstname, about FROM users;
USE `likemind`;

DELIMITER $$
USE `likemind`$$
CREATE DEFINER = CURRENT_USER TRIGGER `likemind`.`users_events_BEFORE_INSERT` BEFORE INSERT ON `users_events` FOR EACH ROW
BEGIN
	DECLARE admin_id INT DEFAULT 1;
	SELECT 
    role_id
INTO admin_id FROM
    roles
WHERE
    roles.role LIKE 'admin';
    
    IF (EXISTS (SELECT * FROM users_events WHERE users_events.event_id = New.event_id AND users_events.role_id = admin_id AND New.role_id = admin_id))
    THEN
		signal sqlstate '45000' set message_text = 'There can only be one admin in an event';
    END IF;
END$$

USE `likemind`$$
CREATE DEFINER = CURRENT_USER TRIGGER `likemind`.`users_events_BEFORE_UPDATE` BEFORE UPDATE ON `users_events` FOR EACH ROW
BEGIN
  DECLARE admin_id INT DEFAULT 1;
	SELECT 
    role_id
INTO admin_id FROM
    roles
WHERE
    roles.role LIKE 'admin';
    
    IF (EXISTS (SELECT * FROM users_events WHERE users_events.event_id = New.event_id AND users_events.role_id = admin_id AND New.role_id = admin_id))
    THEN
    signal sqlstate '45000' set message_text = 'There can only be one admin in an event';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `likemind`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `likemind`;
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (1, 'nikosha', 'nikosha@mail.ru', 'nikpass1', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'Nikolay', 'Я ем лошкой акрошку лепешку кортошьку', 'm');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (2, 'simual', 's11m3@outlook.com', 'jC#jm!p', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'SmPll', 'Jajajaja', 'm');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (3, 'qwerty', 'qwerty@mail.mail', 'qwerty123', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'qwerty', 'qwerty', 'm');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (4, 'jane_blow', 'jannet_sb@yahoo.com', 'krap_mit_002', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'Jannet', 'Lol', 'f');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (5, 'enot', 'enot@enot.ru', 'enotikkotik', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'Enot', 'enot', 'm');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (6, 'kot', 'kot@mail.ru', 'kot', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'Kot', 'kot', 'm');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (7, 'sobaka', 'sobaka@mail.ru', 'sobaka', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'Sobaka', 'sobaka', 'f');
INSERT INTO `likemind`.`users` (`user_id`, `username`, `email`, `password`, `created_at`, `updated_at`, `firstname`, `about`, `sex`) VALUES (8, 'pes', 'pes@mail.ru', 'pes', '2024-01-15 12:24:02', '2024-01-15 12:24:02', 'Pes', 'pes', 'm');

COMMIT;


-- -----------------------------------------------------
-- Data for table `likemind`.`events`
-- -----------------------------------------------------
START TRANSACTION;
USE `likemind`;
INSERT INTO `likemind`.`events` (`event_id`, `title`, `lat`, `lon`, `created_at`, `updated_at`, `limited`, `max_members`, `description`) VALUES (1, 'kushot', 55, 38, '2024-01-15 12:24:02', '2024-01-15 12:24:02', 0, 4, 'идём кушот');
INSERT INTO `likemind`.`events` (`event_id`, `title`, `lat`, `lon`, `created_at`, `updated_at`, `limited`, `max_members`, `description`) VALUES (2, 'pit', 55, 39, '2024-01-15 12:24:02', '2024-01-15 12:24:02', 1, 2, 'идём пит');

COMMIT;


-- -----------------------------------------------------
-- Data for table `likemind`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `likemind`;
INSERT INTO `likemind`.`roles` (`role_id`, `role`) VALUES (1, 'admin');
INSERT INTO `likemind`.`roles` (`role_id`, `role`) VALUES (2, 'moder');
INSERT INTO `likemind`.`roles` (`role_id`, `role`) VALUES (3, 'spoon');

COMMIT;


-- -----------------------------------------------------
-- Data for table `likemind`.`users_events`
-- -----------------------------------------------------
START TRANSACTION;
USE `likemind`;
INSERT INTO `likemind`.`users_events` (`user_id`, `event_id`, `role_id`) VALUES (1, 1, 1);
INSERT INTO `likemind`.`users_events` (`user_id`, `event_id`, `role_id`) VALUES (2, 1, 3);
INSERT INTO `likemind`.`users_events` (`user_id`, `event_id`, `role_id`) VALUES (3, 1, 2);
INSERT INTO `likemind`.`users_events` (`user_id`, `event_id`, `role_id`) VALUES (4, 2, 1);
INSERT INTO `likemind`.`users_events` (`user_id`, `event_id`, `role_id`) VALUES (5, 2, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `likemind`.`images`
-- -----------------------------------------------------
START TRANSACTION;
USE `likemind`;
INSERT INTO `likemind`.`images` (`image_id`, `user_id`, `URN`) VALUES (1, 1, '/srv/img/0.jpg');
INSERT INTO `likemind`.`images` (`image_id`, `user_id`, `URN`) VALUES (2, 3, '/srv/img/1.jpg');
INSERT INTO `likemind`.`images` (`image_id`, `user_id`, `URN`) VALUES (3, 1, '/srv/img/2.jpg');
INSERT INTO `likemind`.`images` (`image_id`, `user_id`, `URN`) VALUES (4, 6, '/srv/img/3.jpg');

COMMIT;

